version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8876:80
    depends_on:
      - app # Это правило для nginx чтобы он запускался только после того как запустится `php`

  app: 
    image: php:8.2-fpm
    build: 
      context: .
      dockerfile: _docker/app/DockerFile
    volumes:
      - ./:/var/www
    container_name: app
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laradocker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci